# Generated by Django 5.0.6 on 2024-06-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertaagua',
            name='alert_conta',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
