# Generated by Django 3.2.25 on 2024-04-12 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoEnergia',
            fields=[
                ('id_contrato_energia', models.AutoField(primary_key=True, serialize=False)),
                ('fornecedor', models.CharField(max_length=10000)),
                ('num_instalacao', models.CharField(max_length=10000)),
                ('num_medidor', models.CharField(max_length=10000)),
                ('num_cliente', models.CharField(max_length=10000)),
                ('modalidade', models.CharField(max_length=10000)),
                ('forma_pagto', models.CharField(max_length=10000)),
                ('email_energia', models.CharField(max_length=10000)),
                ('cidade', models.CharField(max_length=10000)),
                ('num_contrato', models.CharField(max_length=10000)),
                ('hor_ponta', models.CharField(max_length=10000)),
                ('dem_ponta', models.CharField(max_length=10000)),
                ('dem_fora_ponta', models.CharField(max_length=10000)),
                ('data_extra', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ProEnergia',
            fields=[
                ('id_pro_energia', models.AutoField(primary_key=True, serialize=False)),
                ('leitura_anterior', models.CharField(max_length=10000)),
                ('leitura_atual', models.CharField(max_length=10000)),
                ('demanda_faturada_kw', models.CharField(max_length=10000)),
                ('total', models.CharField(max_length=10000)),
                ('fornecedor', models.CharField(max_length=10000)),
                ('num_instalacao', models.CharField(max_length=10000)),
                ('num_cliente', models.CharField(max_length=10000)),
                ('modalidade', models.CharField(max_length=10000)),
                ('num_contrato', models.CharField(max_length=10000)),
                ('ben_tar_bruto', models.CharField(max_length=10000)),
                ('ben_tar_liq', models.CharField(max_length=10000)),
                ('data_extra', models.JSONField()),
                ('contrato_energia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energia.contratoenergia')),
            ],
        ),
        migrations.CreateModel(
            name='AlertaEnergia',
            fields=[
                ('id_alerta', models.AutoField(primary_key=True)),
                ('id_user_alerta', models.CharField(max_length=10000)),
                ('alert_user_email', models.CharField(max_length=10000)),
                ('alert_consumo_media', models.CharField(max_length=10000)),
                ('alert_consumo_atual', models.CharField(max_length=10000)),
                ('alert_conta', models.CharField(max_length=10000)),               
            ]
        ),
    ]
