# Generated by Django 3.2.25 on 2024-04-12 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proenergia',
            name='contrato_energia',
        ),
    ]
