# Generated by Django 5.0.3 on 2024-05-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energia', '0002_remove_proenergia_contrato_energia'),
    ]
