# Generated by Django 3.2.25 on 2024-05-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energia', '0002_remove_proenergia_contrato_energia'),
    ]
