# Generated by Django 3.2.25 on 2024-05-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energia', '0002_remove_proenergia_contrato_energia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertaenergia',
            name='alert_consumo_atual',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='alertaenergia',
            name='alert_consumo_media',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='alertaenergia',
            name='alert_user_email',
            field=models.EmailField(max_length=1000),
        ),
    ]
