# Generated by Django 5.0.3 on 2024-05-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energia', '0003_alter_contratoenergia_dem_fora_ponta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proenergia',
            name='con_fp_cad',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='proenergia',
            name='con_fp_ind',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='proenergia',
            name='con_pt_vd',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='proenergia',
            name='dem_fp_cad',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='proenergia',
            name='dem_fp_ind',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
