# Generated by Django 5.0.3 on 2024-05-20 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energia', '0003_alter_contratoenergia_dem_fora_ponta_and_more'),
        ('energia', '0003_auto_20240504_0250'),
    ]

    operations = [
    ]
