# Generated by Django 3.2.25 on 2024-05-20 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energia', '0004_merge_20240520_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proenergia',
            name='contrato_energia',
        ),
        migrations.AlterField(
            model_name='contratoenergia',
            name='dem_fora_ponta',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='contratoenergia',
            name='dem_ponta',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='contratoenergia',
            name='hor_ponta',
            field=models.CharField(max_length=1000),
        ),
    ]
