# Generated by Django 5.0.3 on 2024-05-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energia', '0004_proenergia_con_fp_cad_proenergia_con_fp_ind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proenergia',
            name='grupos',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
