# Generated by Django 5.0.3 on 2024-05-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energia', '0005_proenergia_grupos'),
    ]

    operations = [
        migrations.AddField(
            model_name='proenergia',
            name='dem_pt',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
