# Generated by Django 5.0.3 on 2024-05-12 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energia', '0006_proenergia_dem_pt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContratoEnergia',
        ),
        migrations.DeleteModel(
            name='ProEnergia',
        ),
    ]
