# Generated by Django 5.0.6 on 2024-05-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('energia', '0007_delete_contratoenergia_delete_proenergia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteContrato',
            fields=[
                ('id_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_contrato', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('ativo', models.CharField(max_length=255)),
                ('num_contrato', models.IntegerField()),
                ('num_cliente', models.IntegerField()),
                ('grupo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FatoContratoEnergia',
            fields=[
                ('id_contrato_energia', models.AutoField(primary_key=True, serialize=False)),
                ('forma_pgto', models.CharField(max_length=255)),
                ('fic_apurado', models.CharField(max_length=255)),
                ('conta_mes', models.CharField(max_length=255)),
                ('demanda_faturada', models.CharField(max_length=255)),
                ('demanda_ultrapassada', models.CharField(max_length=255)),
                ('consumo', models.CharField(max_length=255)),
                ('taxas', models.CharField(max_length=255)),
                ('tarifas', models.CharField(max_length=255)),
                ('nome_contrato', models.CharField(max_length=255)),
                ('num_contrato', models.IntegerField()),
                ('grupo', models.CharField(max_length=255)),
                ('tipo_consumidor', models.CharField(max_length=255)),
                ('num_instalacao', models.IntegerField()),
                ('num_medidor', models.CharField(max_length=255)),
                ('leituras', models.DateField()),
                ('icms', models.CharField(max_length=255)),
                ('dmics', models.CharField(max_length=255)),
                ('dicris', models.CharField(max_length=255)),
                ('dics', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FornecedorEnergia',
            fields=[
                ('id_fornecedor_energia', models.AutoField(primary_key=True, serialize=False)),
                ('fornecedor', models.CharField(max_length=255)),
                ('num_contrato', models.IntegerField()),
                ('grupo', models.CharField(max_length=255)),
            ],
        ),
    ]
