# Generated by Django 5.0.6 on 2024-05-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energia', '0008_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnderecoAgua',
            fields=[
                ('id_endereco', models.AutoField(primary_key=True, serialize=False)),
                ('endereco_instalacao', models.CharField(max_length=255)),
                ('num_contrato', models.IntegerField()),
                ('grupo', models.CharField(max_length=255)),
            ],
        ),
    ]
