# Generated by Django 5.0.6 on 2024-05-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energia', '0009_enderecoagua'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnderecoEnergia',
            fields=[
                ('id_endereco', models.AutoField(primary_key=True, serialize=False)),
                ('endereco_instalacao', models.CharField(max_length=255)),
                ('num_contrato', models.BigIntegerField(null=True)),
                ('grupo', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='EnderecoAgua',
        ),
        migrations.AlterField(
            model_name='clientecontrato',
            name='id_cliente',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clientecontrato',
            name='num_cliente',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='clientecontrato',
            name='num_contrato',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fatocontratoenergia',
            name='num_contrato',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fatocontratoenergia',
            name='num_instalacao',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fornecedorenergia',
            name='num_contrato',
            field=models.BigIntegerField(null=True),
        ),
    ]
