# Generated by Django 5.0.6 on 2024-05-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energia', '0011_alter_clientecontrato_num_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fatocontratoenergia',
            name='consumo',
        ),
        migrations.RemoveField(
            model_name='fatocontratoenergia',
            name='leituras',
        ),
        migrations.RemoveField(
            model_name='fatocontratoenergia',
            name='taxas',
        ),
        migrations.AddField(
            model_name='fatocontratoenergia',
            name='consumo_fp_cap_vd',
            field=models.DecimalField(decimal_places=2, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='fatocontratoenergia',
            name='consumo_fp_ind_vd',
            field=models.DecimalField(decimal_places=2, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='fatocontratoenergia',
            name='consumo_pt_vd',
            field=models.DecimalField(decimal_places=2, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='fatocontratoenergia',
            name='leitura_anterior',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='fatocontratoenergia',
            name='leitura_atual',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='fatocontratoenergia',
            name='taxa_rev_fatura',
            field=models.DecimalField(decimal_places=2, max_digits=1000, null=True),
        ),
    ]
