# Generated by Django 5.0.6 on 2024-05-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energia', '0012_remove_fatocontratoenergia_consumo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatocontratoenergia',
            name='num_contrato',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
