# Generated by Django 5.0.6 on 2024-05-21 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energia', '0014_alter_fatocontratoenergia_num_instalacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enderecoenergia',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='fornecedorenergia',
            name='grupo',
        ),
        migrations.AddField(
            model_name='clientecontrato',
            name='planta',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fatocontratoenergia',
            name='modalidade',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fatocontratoenergia',
            name='planta',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fatocontratoenergia',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=1000, null=True),
        ),
    ]
