# Generated by Django 5.0.6 on 2024-05-21 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energia', '0015_remove_enderecoenergia_grupo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fatocontratoenergia',
            name='forma_pgto',
        ),
        migrations.RemoveField(
            model_name='fatocontratoenergia',
            name='nome_contrato',
        ),
        migrations.AddField(
            model_name='clientecontrato',
            name='forma_pagamento',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
