# Generated by Django 5.0.6 on 2024-05-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energia', '0016_remove_fatocontratoenergia_forma_pgto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientecontrato',
            name='num_instalacao',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
