# Generated by Django 5.0.6 on 2024-05-24 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energia', '0005_auto_20240520_2323'),
        ('energia', '0017_clientecontrato_num_instalacao'),
    ]

    operations = [
    ]
