# Generated by Django 3.2.25 on 2024-04-12 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoAgua',
            fields=[
                ('id_contrato_agua', models.AutoField(primary_key=True, serialize=False)),
                ('fornecedor', models.CharField(max_length=10000)),
                ('num_instalacao', models.CharField(max_length=10000)),
                ('num_medidor', models.CharField(max_length=10000)),
                ('num_cliente', models.CharField(max_length=10000)),
                ('modalidade', models.CharField(max_length=10000)),
                ('num_contrato', models.CharField(max_length=10000)),
                ('tipo_pagto', models.CharField(max_length=10000)),
                ('email_agua', models.CharField(max_length=10000)),
                ('cidade', models.CharField(max_length=10000)),
                ('cod_ligacao_rgi', models.CharField(max_length=10000)),
                ('data_extra', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ProAgua',
            fields=[
                ('id_pro_agua', models.AutoField(primary_key=True, serialize=False)),
                ('leitura_anterior', models.CharField(max_length=10000)),
                ('leitura_atual', models.CharField(max_length=10000)),
                ('consumo_agua_m3', models.CharField(max_length=10000)),
                ('consumo_esgoto_m3', models.CharField(max_length=10000)),
                ('vlr_agua', models.CharField(max_length=10000)),
                ('vlr_esgoto', models.CharField(max_length=10000)),
                ('vlr_total', models.CharField(max_length=10000)),
                ('num_instalacao', models.CharField(max_length=10000)),
                ('num_medidor', models.CharField(max_length=10000)),
                ('num_cliente', models.CharField(max_length=10000)),
                ('cod_ligacao_rgi', models.CharField(max_length=10000)),
                ('num_contrato', models.CharField(max_length=10000)),
                ('data_extra', models.JSONField()),
                ('contrato_agua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agua.contratoagua')),
            ],
        ),
    ]
