# Generated by Django 5.0.6 on 2024-05-24 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteContrato',
            fields=[
                ('nome_contrato', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('ativo', models.CharField(max_length=255)),
                ('numero_contrato', models.BigIntegerField(null=True)),
                ('numero_cliente', models.BigIntegerField(null=True)),
                ('codigo_de_ligacao_rgi', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id_endereco', models.AutoField(primary_key=True, serialize=False)),
                ('endereco_instalacao', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FornecedorAgua',
            fields=[
                ('id_fornecedor_agua', models.AutoField(primary_key=True, serialize=False)),
                ('fornecedor', models.CharField(max_length=255)),
                ('cod_companhia', models.CharField(max_length=255)),
                ('planta', models.CharField(max_length=255)),
                ('codigo_de_ligacao_rgi', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FatoContratoAgua',
            fields=[
                ('id_contrato_agua', models.AutoField(primary_key=True, serialize=False)),
                ('consumo_agua_m3', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('consumo_esgoto_m3', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('vlr_agua', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('vlr_esgoto', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('vlr_total', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('leitura_anterior', models.DateField(null=True)),
                ('leitura_atual', models.DateField(null=True)),
                ('codigo_de_ligacao_rgi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agua.clientecontrato')),
                ('id_endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agua.endereco')),
            ],
        ),
    ]
