# Generated by Django 3.2.25 on 2024-04-12 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proagua',
            name='contrato_agua',
        ),
    ]
