# Generated by Django 5.0.3 on 2024-05-12 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id_endereco', models.AutoField(primary_key=True, serialize=False)),
                ('endereco_instalacao', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FornecedorAgua',
            fields=[
                ('id_fornecedor_agua', models.AutoField(primary_key=True, serialize=False)),
                ('fornecedor', models.CharField(max_length=255)),
                ('cod_companhia', models.IntegerField()),
                ('planta', models.CharField(max_length=255)),
                ('codigo_de_ligacao_rgi', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='proagua',
            name='contrato_agua',
        ),
        migrations.CreateModel(
            name='FatoContratoAgua',
            fields=[
                ('id_contrato_agua', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_de_ligacao_rgi', models.IntegerField()),
                ('consumo_agua_m3', models.IntegerField()),
                ('consumo_esgoto_m3', models.IntegerField()),
                ('vlr_agua', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vlr_esgoto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vlr_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('leitura_anterior', models.DateField()),
                ('leitura_atual', models.DateField()),
                ('id_endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agua.endereco')),
            ],
        ),
        migrations.DeleteModel(
            name='ContratoAgua',
        ),
        migrations.DeleteModel(
            name='ProAgua',
        ),
    ]
