# Generated by Django 5.0.3 on 2024-05-12 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0002_endereco_fornecedoragua_remove_proagua_contrato_agua_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteContrato',
            fields=[
                ('id_cliente', models.IntegerField()),
                ('nome_contrato', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('ativo', models.CharField(max_length=1)),
                ('numero_contrato', models.IntegerField()),
                ('numero_cliente', models.IntegerField()),
                ('codigo_de_ligacao_rgi', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cidade',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='id_endereco',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fatocontratoagua',
            name='consumo_agua_m3',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fatocontratoagua',
            name='consumo_esgoto_m3',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fatocontratoagua',
            name='id_contrato_agua',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fornecedoragua',
            name='codigo_de_ligacao_rgi',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='fornecedoragua',
            name='fornecedor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fornecedoragua',
            name='id_fornecedor_agua',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fornecedoragua',
            name='planta',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fatocontratoagua',
            name='codigo_de_ligacao_rgi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agua.clientecontrato'),
        ),
    ]
