# Generated by Django 5.0.3 on 2024-05-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0003_clientecontrato_alter_endereco_cidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientecontrato',
            name='id_cliente',
        ),
        migrations.AlterField(
            model_name='clientecontrato',
            name='ativo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clientecontrato',
            name='codigo_de_ligacao_rgi',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cidade',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='id_endereco',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fatocontratoagua',
            name='consumo_agua_m3',
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='fatocontratoagua',
            name='consumo_esgoto_m3',
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='fatocontratoagua',
            name='id_contrato_agua',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fatocontratoagua',
            name='vlr_agua',
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='fatocontratoagua',
            name='vlr_esgoto',
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='fatocontratoagua',
            name='vlr_total',
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='fornecedoragua',
            name='cod_companhia',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fornecedoragua',
            name='codigo_de_ligacao_rgi',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='fornecedoragua',
            name='fornecedor',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fornecedoragua',
            name='id_fornecedor_agua',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fornecedoragua',
            name='planta',
            field=models.CharField(max_length=255),
        ),
    ]
