# Generated by Django 5.0.3 on 2024-05-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0005_alter_clientecontrato_numero_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientecontrato',
            name='numero_cliente',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='clientecontrato',
            name='numero_contrato',
            field=models.BigIntegerField(),
        ),
    ]
