# Generated by Django 5.0.3 on 2024-05-14 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0006_alter_clientecontrato_numero_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientecontrato',
            name='nome_contrato',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
