# Generated by Django 5.0.3 on 2024-05-14 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0007_alter_clientecontrato_nome_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientecontrato',
            name='numero_contrato',
            field=models.BigIntegerField(null=True),
        ),
    ]
