# Generated by Django 5.0.3 on 2024-05-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0008_alter_clientecontrato_numero_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatocontratoagua',
            name='leitura_anterior',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='fatocontratoagua',
            name='leitura_atual',
            field=models.DateField(null=True),
        ),
    ]
