# Generated by Django 5.0.3 on 2024-04-01 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados', models.JSONField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('documento', models.CharField(choices=[('fatura', 'Fatura'), ('contrato', 'Contrato')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Energia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados', models.JSONField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('documento', models.CharField(choices=[('fatura', 'Fatura'), ('contrato', 'Contrato')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados', models.JSONField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('documento', models.CharField(choices=[('fatura', 'Fatura'), ('contrato', 'Contrato')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
