name: Deploy Tecsus

on:
  push:
    branches:
      - XP-36-integracao

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Docker Image
        run: docker build -t datateam23/tecsus-backend .
        working-directory: tecsus

      - name: Push Docker Image
        run: docker push datateam23/tecsus-backend
        working-directory: tecsus
       
       
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
        - name: Pull Docker image for backend
          run: sudo docker pull datateam23/tecsus-backend:latest

        - name: Run Database
          run: sudo docker run -d --name postgres-db -e POSTGRES_DB=${{secrets.DATABASE_NAME}} -e POSTGRES_USER=${{secrets.DATABASE_user}} -e POSTGRES_PASSWORD=${{secrets.DATABASE_PASSWORD}} -v postgres_data:/var/lib/postgresql/data postgres:latest
  
        - name: Run Django makemigrations
          run: sudo docker run --rm --name django-makemigrations --link postgres-db:db -e DATABASE_URL=${{secrets.DATABASE_URL}} datateam23/tecsus-backend python manage.py makemigrations
  
        - name: Run Django migrations
          run: sudo docker run --rm --name django-migrate --link postgres-db:db -e DATABASE_URL=${{secrets.DATABASE_URL}} datateam23/tecsus-backend python manage.py migrate
  
        - name: Create Django superuser
          run: sudo docker run --rm --name django-superuser --link postgres-db:db -e DATABASE_URL=${{secrets.DATABASE_URL}} datateam23/tecsus-backend python manage.py createsuperuser
  
        - name: Start Django backend application
          run: sudo docker run -d --name tecsus-backend -p 8000:8000 --link postgres-db:db datateam23/tecsus-backend