name: Deploy Tecsus

on:
  push:
    branches:
      - xp-48-Deploy
  pull_request:
    branches:
      - xp-48-Deploy
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Docker Image
        run: docker build -t datateam23/tecsus-backend .
        working-directory: tecsus

      - name: Push Docker Image
        run: docker push datateam23/tecsus-backend
        working-directory: tecsus
       
       
  deploy:
          needs: build
          runs-on: self-hosted
          steps:
              - name: Pull image from docker hub
                run: sudo docker pull datateam23/tecsus-backend:latest
              - name: Remove docker container
                run: sudo docker rm -f tecsus-backend
              - name: Run docker container
                run: sudo docker run -d -p 8000:8000 -e DATABASE_USERNAME=${{secrets.DATABASE_USER}} -e DATABASE_PASSWORD='${{secrets.DATABASE_PASSWORD}}' -e DATABASE_URL=${{secrets.DATABASE_URL}} --name tecsus-backend  datateam23/tecsus-backend
              - name: Copy migrations script to container
                run: sudo docker cp ./path/to/migrations.bat tecsus-backend:/migrations.bat
              - name: Run migrations script in container
                run: sudo docker exec tecsus-backend bash -c 'chmod +x /migrations.bat && /migrations.bat'

