name: Load Test Pipeline

on:
  push: 
    branches: [xp-49-deploy-banco]

jobs:
  build-unit-tests:
    name: Load Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.5

      - name: permissões start-install.bat
        run: chmod +x ./tecsus/start-install.bat 

      - name: Run start-install.bat
        run: |
            ./start-install.bat
        working-directory: tecsus

      - name: permissões start.bat
        run: chmod +x ./tecsus/start.bat 

      - name: Run start.bat
        run: |
            ./start.bat
        working-directory: tecsus      
        
      - name: Wait for start.bat to complete
        run: |
          while [ ! -f tecsus/completion.txt ]; do
            sleep 1
          done

      - name: Remove completion file
        run: rm tecsus/completion.txt
        
      - name: Run docker exec
        run: docker exec -it tecsus-db-1 bash
        working-directory: tecsus
        
      - name: Run Load Test
        run: psql -U tecsus -d tecsus -f /docker-entrypoint-initdb.d/v1/initial_load.sql
